### ISSUE TITLE
Schedule: Has Many Users Through Schedules_Users

### ISSUE THREAD

**Issue by maxdobeck** [maxdobeck/zeiter#17]
The Schedules model should have many users and a Join table that controls the users role for each Schedule.

**Comment by maxdobeck** [comment]
Creating Schedules in the current branch.  Will test that a user can only see other users that are part of the Schedule.

**Comment by kapoorlakshya** [comment]
Was this fulfilled by PR #29 and can this be closed? Or are they unrelated?

**Comment by maxdobeck** [comment]
I need to extend this issue. There is no mechanism to add or remove users to schedules. Right now users can only modify schedules, not the users in them.

**Comment by maxdobeck** [comment]
I need to extend this issue. There is no mechanism to add or remove users to schedules. Right now users can only modify schedules, not the users in them.

This means modifying the schedules controller and forms for schedules I think. But the first step is done. Assignments are nested under schedules.

**Comment by maxdobeck** [comment]
Pull request #34 resolves the above items and more.

**Comment by maxdobeck** [comment]
Pull Request #34 will have the above features and minor bug fices.

**Comment by kapoorlakshya** [comment]
@maxdobeck I'm running into this error when trying to retrieve all `users` associated to a `Schedule`:

```
rb(main):030:0> sch = Schedule.first.users
  Schedule Load (0.0ms)  SELECT  "schedules".* FROM "schedules" ORDER BY "schedules"."id" ASC LIMIT $1  [["
LIMIT", 1]]
ActiveRecord::HasManyThroughOrderError: Cannot have a has_many :through association 'Schedule#users' which
goes through 'Schedule#enrollments' before the through association is defined.
        from (irb):30
irb(main):031:0>
```
Am I not using the relation correctly?

**Comment by maxdobeck** [comment]
Try this:
I've got the same issue and as @aoozdemir, I solved it by setting
the has_many of the join table before the has_many through.

https://github.com/rails/rails/issues/29123

**Comment by maxdobeck** [comment]
Yeah we just have to go to our models and flip this around.  Declare the has_many before the through association. 

10months ago this was added to rails 5.x https://github.com/rails/rails/pull/27485
