### ISSUE TITLE
UI: Fill Nav Partial on Mobile

### ISSUE THREAD

**Issue by maxdobeck** [maxdobeck/zeiter#26]
Navigation bar doesn't fill available space on mobile. Logo should be more prominent and scale up horizontally and vertically. 

Possibly place login and signup links in navbar to avoid mobile users relying on hamburger menu during login.

**Comment by kapoorlakshya** [comment]
It's bootstrap that automatically puts all links in the hamburger menu on small screen devices. Will have to check the docs to see how to avoid that.

**Comment by maxdobeck** [comment]
Okay worst case we can just leave it as is. Minor thing but when I was
clicking on the test environment it was hard to hit with my fingers.

**Comment by maxdobeck** [comment]
We'll deal with Mobile design at a later date.
